R_inv: !!python/object/apply:builtins.getattr
- &id001 !!python/object:dataGeneration.MassSpringChain
  N: 3
  dt: 0.1
  length: 25
  q: 0
  r: 0
  state_dim: 6
- R_inv
backbone_parameters:
  hidden_dim: 64
  num_residual_blocks: 5
  time_emb_dim: 256
context_length: 200
diffusion_scheduler: !!python/name:sfdiff.utils.linear_beta_schedule ''
dropout_rate: 0.01
h_fn: !!python/object/apply:builtins.getattr
- *id001
- h_fn
init_skip: true
lr: 0.001
modelType: s5
observation_dim: 3
prediction_length: 50
timesteps: 200
use_transformer: false
